/**
 * Filament dryer: the printer-owned half.
 *
 * `dryer-core.ts` and `server/dryer.ts` between them run a drying session from *here*:
 * the service sets a bed target with `1028` and re-asserts it every 30 s, because
 * anything that clears the target reads exactly like a session running normally. That
 * keepalive is the whole safety argument, and it has one hole it cannot close: it only
 * works while the service is alive. Kill the container, lose the network, reboot the
 * host mid-session, and the bed is left at temperature with nothing re-asserting it and
 * nothing to turn it off.
 *
 * This file closes that hole by handing the job to the machine that owns the heater. A
 * drying cycle expressed as gcode and started as an ordinary print is held by the
 * printer's own job runner: `M140` inside a running job survives the service dying, the
 * browser closing and the network dropping, and the trailing `M140 S0` runs off the
 * printer's queue rather than ours.
 *
 * ## Why there is no motion in here
 *
 * No `G28`, and therefore no `G1`. Klipper refuses to move an unhomed axis, so removing
 * the homing removes the plate move with it, and that trade is worth taking, because
 * `G28` probes the plate. A spool already sitting there is something for the nozzle to
 * be driven into. With nothing homing and nothing moving there is no such window, so a
 * spool can be loaded *before* the cycle starts rather than during a timed gap.
 *
 * The plate is positioned by hand beforehand, with the Z controls on the dashboard.
 *
 * ## Why many short dwells
 *
 * One `G4` of six hours would be simpler and worse: a cancel has to wait out whatever
 * remains of the dwell already queued. Sixty-second dwells bound that wait to a minute.
 *
 * Pure, and free of DOM, network and clock, so the output can be asserted directly.
 */

import { MAX_SAFE_C, clampMinutes, clampTemp } from './dryer-core';

/** How long each dwell holds. Sets the worst-case delay on a cancel. */
export const DWELL_SECONDS = 60;

/** Dwells per progress message, so the printer's display counts down in half hours. */
const DWELLS_PER_BLOCK = 30;

export interface DryingGcodeOptions {
  /** Bed temperature to hold, °C. Clamped by `clampTemp`. */
  tempC: number;
  /** How long to hold it. Clamped by `clampMinutes`. */
  minutes: number;
  /** Shown on the printer's own display while it runs. */
  label?: string;
}

/**
 * A filename that says what it is at a glance, and that the rest of the service can
 * recognise as ours.
 *
 * The prefix is load-bearing, not decoration: to the printer and to this dashboard a
 * drying cycle is a *print*, so without a marker it lands in the print history, fires
 * "print started" and "print complete" over Telegram, and starts a PDF report. Anything
 * that should skip a drying cycle tests `isDryingFile`.
 */
export const DRYING_FILE_PREFIX = '__dry-';

export function dryingFileName(tempC: number, minutes: number): string {
  const t = clampTemp(tempC);
  const m = clampMinutes(minutes);
  // Minutes rather than hours so a 90-minute cycle is not called "1h" or "2h".
  return `${DRYING_FILE_PREFIX}${t}c-${m}m.gcode`;
}

/** Whether a filename is one of ours, and so not a print anybody wants a report about. */
export function isDryingFile(filename: string): boolean {
  // Match on the basename: the printer lists files under a directory, and a path
  // prefix would otherwise hide the marker.
  const base = filename.split('/').pop() ?? filename;
  return base.startsWith(DRYING_FILE_PREFIX);
}

/**
 * Build the cycle.
 *
 * Both inputs go through the same clamps the panel and the HTTP handler use, so a
 * value that arrives over the wire cannot ask the bed for something the rest of the
 * feature would have refused.
 */
export function buildDryingGcode(options: DryingGcodeOptions): string {
  const tempC = clampTemp(options.tempC);
  const minutes = clampMinutes(options.minutes);
  const label = options.label ?? 'Filament';

  // Round up: a cycle asked for in minutes should never be shorter than requested,
  // and the remainder is at most one dwell.
  const dwells = Math.ceil((minutes * 60) / DWELL_SECONDS);
  const dwellMs = DWELL_SECONDS * 1000;

  const out: string[] = [
    '; ==========================================================================',
    `; ${label}: ${tempC} C bed for ${minutes} min. Nozzle cold, nothing moves.`,
    ';',
    '; Generated by cc2-commander. Safe to delete.',
    ';',
    '; No G28 and no G1, deliberately. Klipper refuses to move an unhomed axis, so',
    '; dropping the homing drops the plate move with it. That is the safe trade:',
    '; G28 probes the plate, and a spool sitting on it is something for the nozzle',
    '; to hit. Nothing here homes, probes or moves, so the spool can already be',
    '; loaded when this starts. Position the plate first with the Z controls.',
    ';',
    `; ${MAX_SAFE_C} C is the ceiling everywhere in this project: above it a spool can`,
    '; soften onto the plate.',
    '; ==========================================================================',
    '',
    'M104 S0          ; nozzle off, and it stays off for the whole cycle',
    'M107             ; fans off',
    '',
    `M117 Heating bed to ${tempC}C`,
    `M140 S${tempC}`,
    `M190 S${tempC}          ; wait until the bed is actually there`,
    '',
    `; hold: ${dwells} x ${DWELL_SECONDS}s dwells. Short ones so a cancel lands promptly.`,
  ];

  for (let i = 0; i < dwells; i++) {
    if (i % DWELLS_PER_BLOCK === 0) {
      const remaining = Math.round(((dwells - i) * DWELL_SECONDS) / 60);
      out.push('', `M117 Drying - ${remaining} min left`);
    }
    out.push(`G4 P${dwellMs}`);
  }

  out.push('', 'M140 S0          ; bed off', 'M104 S0', 'M107', 'M117 Dry cycle complete', '');

  return out.join('\n');
}
